version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '9000:9000'
    networks:
      - eficodenet
    volumes:
      - ./backend:/usr/src/app
    
  frontend:
    build: ./frontend
    ports:
      - '8000:8000'
    networks:
      - eficodenet
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app


networks:
  eficodenet:
